# Setup
title:               winnie jeng
tagline:             'class notes'
description:         'This is where I overflow my stack ʕ•́ᴥ•̀ʔっ♡'
url:                 https://winniewjeng.github.io
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Winnie Jeng
  url:               
  email:             winniewjeng@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
excerpt_separator: <!--more-->
# version:             1.1.0
# google_analytics_id: UA-146052-15

# KaTex
markdown: kramdown
kramdown:
  math_engine: katex